#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p usb
cd usb
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "0123456789" > strings/0x409/serialnumber
echo "Connor Brown" > strings/0x409/manufacturer
echo "Smarter Board" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: Touchscreen device" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

mkdir -p functions/hid.usb0
echo 0 > functions/hid.usb0/protocol
echo 0 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne \\x05\\x0D\\x09\\x04\\xA1\\x01\\x85\\x01\\x09\\x22\\xA1\\x02\\x09\\x42\\x15\\x00\\x25\\x01\\x95\\x01\\x75\\x01\\x81\\x02\\x95\\x07\\x81\\x03\\x75\\x08\\x09\\x51\\x95\\x01\\x81\\x02\\x05\\x01\\x26\\xff\\x0f\\x75\\x10\\x55\\x0e\\x65\\x13\\x09\\x30\\x35\\x00\\x46\\xb5\\x04\\x81\\x02\\x46\\x8a\\x03\\x09\\x31\\x81\\x02\\xC0\\x05\\x0D\\x09\\x54\\x26\\xFF\\x00\\x95\\x01\\x75\\x08\\x81\\x02\\xC0 > functions/hid.usb0/report_desc
ln -s functions/hid.usb0 configs/c.1/
ls /sys/class/udc > UDC
